### ISSUE TITLE
window never opens

### ISSUE THREAD

**Issue by Lowentwickler** [KyleMayes/vulkanalia#243] opened 2023-11-20 12:06 UTC
I am starting example like this:
```
$ cd vulkanalia/examples
$ cargo run --release 
```

Window never opens. I did some tests and found out that code bellow never returns:

```
let result = self.device.acquire_next_image_khr(
            self.data.swapchain,
            u64::max_value(),
            self.data.image_available_semaphores[self.frame],
            vk::Fence::null(),
        );
```

I tried to change `u64::max_value()` with `10_000` and got error:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', examples/src/lib.rs:164:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: queue 0x55f012d714f0 destroyed while proxies still attached:
  wl_buffer@42 still attached
  wl_buffer@41 still attached
  wl_buffer@39 still attached
  wl_buffer@40 still attached
  wl_subsurface@34 still attached
  wl_surface@33 still attached
  wl_subsurface@32 still attached
  wl_surface@31 still attached
  wl_subsurface@30 still attached
  wl_surface@29 still attached
  wl_subsurface@28 still attached
  wl_surface@27 still attached
  wl_subsurface@26 still attached
  wl_surface@25 still attached
  xdg_wm_base@23 still attached
  wl_output@15 still attached
  xdg_activation_v1@14 still attached
  zwp_text_input_manager_v3@13 still attached
  zwp_pointer_constraints_v1@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  wl_seat@10 still attached
  wp_fractional_scale_manager_v1@9 still attached
  wp_viewporter@8 still attached
  wl_subcompositor@7 still attached
  wl_output@6 still attached
  wl_shm@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached

```

OS: ArchLinux 6.4.12-arch1-1 x86_64
GPU[0]: "AMD Radeon Graphics (RADV REMBRANDT)" (INTEGRATED_GPU)
GPU[1]: "AMD Radeon RX 6800M (RADV NAVI22)" (DISCRETE_GPU)

The `triangle` example from `ash` works just fine.

Any clue?

**Comment by KyleMayes** [comment] 2024-04-02 02:16
I think this is caused by your swapchain having no images created for it (which causes the indexing panic because of an index into an empty `Vec` of swapchain images and causes the acquisition of a presentable swapchain image to time out).

The number of swapchain images to create is currently calculated as one more than the minimum number of swapchain images allowed and then clamped on the upper end by the maximum number of swapchain images allowed:

https://github.com/KyleMayes/vulkanalia/blob/29dec0b7dc2a7d304d264ec1af7ff9c5c744dd22/examples/src/lib.rs#L524

Those min and max values are coming from [`VkSurfaceCapabilitiesKHR`](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesKHR.html), which says that the maximum number of swapchain images may be `0` in cases where the Vulkan implementation does not enforce a limit.

So I think in your case, your Vulkan implementation is reporting a maximum swapchain image count of `0` which breaks the above logic since it will always be limited to `0`. 

The fix is to add handling for this case and don't do the upper limit clamping when the upper limit is 0.

I'll need to update both the example code and tutorial.

**Comment by KyleMayes** [comment] 2024-04-02 02:41
The max image count being 0 was already being properly handled in the tutorial, I just failed to replicate the same logic in the triangle example. In any case, I believe this issue should be fixed.

**Closed by KyleMayes** 2024-04-02 02:41 UTC
Labels: bug
